# Generated by Django 3.2.13 on 2022-05-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
