# Generated by Django 3.2.13 on 2022-05-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0002_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
