# Generated by Django 3.2.13 on 2022-05-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0008_alter_cwusers_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
